#!/usr/bin/env bash

set -eu pipefail

# cmake 3.5.2
DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
export PATH=${DEPS_DIR}/bin:${PATH} && mkdir -p ${DEPS_DIR}
CMAKE_URL="https://mason-binaries.s3.amazonaws.com/${TRAVIS_OS_NAME}-x86_64/cmake/3.5.2.tar.gz"
travis_retry wget --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}

apt-get install libboost-all-dev g++ -y
